version: '3'
networks:
  dotbit:
    ipam:
      driver: default
      config:
        - subnet: 182.17.0.0/16
          gateway: 182.17.0.1

services:
  did-indexer-svr:
    image: admindid/did-indexer-svr:latest
    restart: always
    working_dir: /app
    entrypoint: [ "/app/did-indexer-svr", "--config", "/app/config/config.yaml" ]
    ports:
      - ${DID_INDEXER_SVR_PORT:-9132}:9132
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
    depends_on:
      - mysql
    networks:
      - dotbit
    extra_hosts:
      - host.docker.internal:host-gateway
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  mysql:
    image: mysql/mysql-server:8.0
    restart: always
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DAS_DB_PORT:-123456}
      MYSQL_DATABASE: d_did_indexer
      TZ: Asia/Shanghai
      # This allows ip ranges from 182.17.0.1 to 182.17.255.255 to connect to root
      MYSQL_ROOT_HOST: "182.17.%.%"
    networks:
      - dotbit
    extra_hosts:
      - host.docker.internal:host-gateway
