server:
  is_update: false
  name: "did-indexer-svr"
  net: 2
  http_port: ":8132"
  pay_server_address: ""
  pay_private: ""
  remote_sign_api_url: ""
  tx_fee_rate: 1
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "123456"
    db_name: "d_indexer"
  redis:
    addr: ""
    password: ""
    db_num: 0
chain:
  ckb:
    node: ""
    current_block_number: 13184725 # testnet-13184725
    confirm_num: 4
    concurrency_num: 100

