server:
  name: "dp-svr"
  net: 2
  http_port: ":8132"
  http_port_internal: ":8133"
  uni_pay_url: ""
  min_deposit_amount: "30"
  refund_switch: true
  transfer_whitelist: ""
  transfer_whitelist_private: ""
  capacity_whitelist: ""
  capacity_whitelist_private: ""
  split_count: 2
  split_amount: 20000000
  remote_sign_api_url: ""
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: ""
    db_name: "d_dp"
  parser_mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: ""
    db_name: "d_dp"
  redis:
    addr: ""
    password: ""
    db_num: 0
chain:
  ckb:
    node: ""
    current_block_number: 11195338 # testnet2 11195338
    confirm_num: 4
    concurrency_num: 100
unipay_address_map:
  "evm": ""
  "tron": ""
stripe:
  premium_percentage: ""
  premium_base: ""
