server:
  is_update: false
  name: "did-indexer-svr"
  net: 2 # 2-testnet, 1-mainnet
  http_port: ":9132"
db:
  mysql:
    addr: "127.0.0.1:3306" # 172.17.0.1: docker 182.17.0.1: docker-compose
    user: "root"
    password: ""
    db_name: "did_indexer"
  redis:
    addr: "localhost:6379" # 172.17.0.1: docker 182.17.0.1: docker-compose
    password: ""
    db_num: 0
chain:
  ckb:
    node: "https://testnet.ckb.dev"
    current_block_number: 13184725 # 13184725-testnet2, 13226009-mainnet
    confirm_num: 4
    concurrency_num: 100

