server:
  is_update: false
  name: "did-indexer-svr"
  net: 2 # 2-testnet, 1-mainnet
  http_port: ":9132"
db:
  mysql:
    addr: "docker.for.mac.localhost:3306" # 172.17.0.1: docker; 182.17.0.1: docker-compose; docker.for.mac.localhost
    user: "root"
    password: "123456"
    db_name: "did_indexer"
  redis:
    addr: "docker.for.mac.localhost:6379" # 172.17.0.1: docker; 182.17.0.1: docker-compose; docker.for.mac.localhost
    password: ""
    db_num: 0
chain:
  ckb:
    node: "https://testnet.ckb.dev"
    current_block_number: 13184725 # 13184725-testnet2, 13337722-mainnet
    confirm_num: 4
    concurrency_num: 100

