server:
  is_update: false
  name: "did-indexer-svr"
  net: 2 # 2-testnet, 1-mainnet
  http_port: ":9132"
  pay_server_address: ""
  pay_private: ""
  remote_sign_api_url: ""
  tx_fee_rate: 1
origins:
notify:
  sentry_dsn: ""
  lark_err_key: ""
  prometheus_push_gateway: ""
db:
  mysql:
    addr: "127.0.0.1:3306"
    user: "root"
    password: "tzh123456"
    db_name: "did_indexer"
  redis:
    addr: "localhost:6379"
    password: ""
    db_num: 0
chain:
  ckb:
    node: "https://testnet.ckb.dev"
    current_block_number: 13184725 # 13184725-testnet2, 13337722-mainnet
    confirm_num: 4
    concurrency_num: 100

